apiVersion: numaflow.numaproj.io/v1alpha1
kind: InterStepBufferService
metadata:
  name: default
spec:
  jetstream:
    version: 2.9.15
    replicas: 3
    persistence:
      accessMode: ReadWriteOnce
      volumeSize: 15Gi
