apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- https://github.com/numaproj/numaflow/config/advanced-install/namespaced-controller?ref=v1.0.0-rc3
- https://github.com/numaproj/numaflow/config/advanced-install/namespaced-numaflow-server?v1.0.0-rc3
- redis
- ingestor
- isbsvc.yaml
- https://raw.githubusercontent.com/numaproj-labs/log-summarization/main/log_summarization_pipeline.yaml

namespace: numaproj-assist

images:
- name: quay.io/numaproj/numaflow
  newTag: v1.0.0-rc3
