apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/numaio/log-ingestor
    newName: quay.io/numaio/log-ingestor
    newTag: v0.0.7

resources:
  - https://github.com/numaproj-labs/log-ingestor/manifests/install?ref=main

patchesStrategicMerge:
  - log-ingestor-config-patch.yaml
  - log-ingestor-deployment-patch.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DEBUG_MODE
          value: "true"
    target:
      kind: Deployment
      name: log-ingestor
