apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-ingestor
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: main
          args:
            - --ingestion-url=https://log-summarization-pipeline-in:8443/vertices/in
            - --lookback-duration=20s
            - --task-interval=10000
