apiVersion: numaflow.numaproj.io/v1alpha1
kind: InterStepBufferService
metadata:
  name: log-summarization
spec:
  redis:
    native:
      persistence:
        accessMode: ReadWriteOnce
        volumeSize: 20Gi
      settings:
        redis: |
          min-replicas-to-write 1
          # Disable RDB persistence, AOF persistence already enabled.
          save ""
          # Enable AOF https://redis.io/topics/persistence#append-only-file
          appendonly yes
          auto-aof-rewrite-percentage 100
          auto-aof-rewrite-min-size 64mb
          maxmemory 1800mb
          maxmemory-policy allkeys-lru
      version: 7.0.11
