apiVersion: numaflow.numaproj.io/v1alpha1
kind: InterStepBufferService
metadata:
  name: log-summarization
spec:
  redis:
    native:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: isbsvc
                  numaflow.numaproj.io/isbsvc-name: log-summarization
              #topologyKey: topology.kubernetes.io/zone
              topologyKey: kubernetes.io/hostname
            weight: 100
      containerTemplate:
        resources:
          limits:
            memory: 2048Mi
          requests:
            cpu: 2
            memory: 2048Mi
      persistence:
        accessMode: ReadWriteOnce
        volumeSize: 20Gi
      settings:
        redis: |
          min-replicas-to-write 1
          # Disable RDB persistence, AOF persistence already enabled.
          save ""
          # Enable AOF https://redis.io/topics/persistence#append-only-file
          appendonly yes
          auto-aof-rewrite-percentage 100
          auto-aof-rewrite-min-size 64mb
          maxmemory 1800mb
          maxmemory-policy allkeys-lru
      version: 7.0.11
