{
 "title": "numaflow-dashboard",
 "description": "A sample numaflow dashboard for reference",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pipeline",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"}, pipeline)"
    }
   },
   {
    "name": "vertex",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pipeline=~\"$pipeline\"}, vertex)"
    }
   },
   {
    "name": "buffer",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pipeline=~\"$pipeline\", vertex=~\"$vertex\"}, partition_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency (_bucket 50%-ile)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_forward_chunk_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_read_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_write_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_ack_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filter Resize",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_forward_chunk_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_read_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_write_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_ack_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_udf_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inference",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_forward_chunk_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_read_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_write_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_ack_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_udf_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_forward_chunk_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_read_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_write_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_ack_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval])) / 1000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Latency (_sum / _count)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "(rate(forwarder_forward_chunk_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval]) / 1000) / rate(forwarder_forward_chunk_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_read_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval]) / 1000) / rate(forwarder_read_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_write_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval]) / 1000) / rate(forwarder_write_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_ack_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval]) / 1000) / rate(forwarder_ack_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filter Resize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "(rate(forwarder_forward_chunk_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval]) / 1000) / rate(forwarder_forward_chunk_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_read_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval]) / 1000) / rate(forwarder_read_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_write_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval]) / 1000) / rate(forwarder_write_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_ack_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval]) / 1000) / rate(forwarder_ack_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_udf_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval]) / 1000) / rate(forwarder_udf_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(rate(forwarder_forward_chunk_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval]) / 1000) / rate(forwarder_forward_chunk_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_read_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval]) / 1000) / rate(forwarder_read_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_write_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval]) / 1000) / rate(forwarder_write_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_ack_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval]) / 1000) / rate(forwarder_ack_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_udf_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval]) / 1000) / rate(forwarder_udf_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(rate(forwarder_forward_chunk_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval]) / 1000) / rate(forwarder_forward_chunk_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_read_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval]) / 1000) / rate(forwarder_read_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_write_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval]) / 1000) / rate(forwarder_write_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_ack_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval]) / 1000) / rate(forwarder_ack_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forward Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(rate(forwarder_forward_chunk_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval]) / 1000) / rate(forwarder_forward_chunk_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"in\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_forward_chunk_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval]) / 1000) / rate(forwarder_forward_chunk_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"filter-resize\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_forward_chunk_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval]) / 1000) / rate(forwarder_forward_chunk_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"inference\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "(rate(forwarder_forward_chunk_processing_time_sum{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval]) / 1000) / rate(forwarder_forward_chunk_processing_time_count{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"out\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Forwarder E2E - Batch Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_forward_chunk_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "histogram_quantile(0.9, rate(forwarder_forward_chunk_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "histogram_quantile(0.99, rate(forwarder_forward_chunk_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Read Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_read_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "histogram_quantile(0.9, rate(forwarder_read_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "histogram_quantile(0.99, rate(forwarder_read_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "UDF - Batch Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_udf_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "histogram_quantile(0.9, rate(forwarder_udf_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "histogram_quantile(0.99, rate(forwarder_udf_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Write Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(forwarder_write_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "histogram_quantile(0.9, rate(forwarder_write_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      },
      {
       "expr": "histogram_quantile(0.99, rate(forwarder_write_processing_time_bucket{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])) / 1000",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Inbound Messages(TPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 333 },
     "targets": [
      {
       "expr": "rate(forwarder_read_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inbound Data Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 333 },
     "targets": [
      {
       "expr": "rate(forwarder_read_bytes_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outbound Messages(TPS)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 333 },
     "targets": [
      {
       "expr": "rate(forwarder_write_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "UDF Inbound Messages(TPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 342 },
     "targets": [
      {
       "expr": "rate(forwarder_udf_read_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "UDF Outbound Messages(TPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 342 },
     "targets": [
      {
       "expr": "rate(forwarder_udf_write_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ack'ed Messages(TPS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 342 },
     "targets": [
      {
       "expr": "rate(forwarder_ack_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 951 },
     "targets": [
      {
       "expr": "rate(forwarder_read_error_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 951 },
     "targets": [
      {
       "expr": "rate(forwarder_write_error_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ack Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 951 },
     "targets": [
      {
       "expr": "rate(forwarder_ack_error_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "UDF Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 958 },
     "targets": [
      {
       "expr": "rate(forwarder_udf_error_total{namespace=\"$namespace\", pipeline=\"$pipeline\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Platform Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 958 },
     "targets": [
      {
       "expr": "rate(forwarder_platform_error_total{namespace=\"$namespace\", pipeline=\"$pipeline\", vertex=\"$vertex\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturation Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "IsFull",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 952 },
     "targets": [
      {
       "expr": "rate(isb_jetstream_isFull_total{buffer=\"$buffer\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 952 },
     "targets": [
      {
       "expr": "isb_jetstream_buffer_soft_usage{buffer=\"$buffer\"}*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pending Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 952 },
     "targets": [
      {
       "expr": "isb_jetstream_buffer_pending{buffer=\"$buffer\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ack Pending Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 952 },
     "targets": [
      {
       "expr": "isb_jetstream_buffer_ack_pending{buffer=\"$buffer\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}