- name: Check if each host has NVIDIA devices
  ansible.builtin.command: lspci
  register: nvidia_driver_lspci
  changed_when: false

- name: Continue to install
  when: >
    "nvidia" in nvidia_driver_lspci.stdout|lower
  ansible.builtin.import_tasks: main2.yml
