[tool.poetry]
name = "dci-poc-vertex-gpu-fr"
version = "1.0.3"
description = "GPU-utilizing filter resize Vertex that composes the dci_poc pipeline"
authors = ["tmenjo"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pynumaflow = "0.14.0"

opencv-python = "4.10.0.84"
numpy = "2.2.2"
PyTurboJPEG = "1.7.7"
msgspec = "^0.20.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-asyncio = "^1.3.0"
pytest-cov = "^3.0"
python-dotenv = "1.0.1"
pathlib = "1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
