- name: Ensure that $HOME/git directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/git"
    state: directory
    mode: "0755"

- name: Checkout kube-prometheus
  ansible.builtin.git:
    repo: https://github.com/prometheus-operator/kube-prometheus.git
    dest: "{{ ansible_facts['env']['HOME'] }}/git/kube-prometheus"
    version: "v{{ kube_prometheus.kube_prometheus_ver }}"

# Installing/Updating kube-prometheus is simple; apply manifests as follows:
#
#   $ kubectl apply --server-side -f manifests/setup
#   $ kubectl apply -f manifests/
#
# See the following links for details:
#
# - https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/update.md#compile-the-manifests-and-apply
# - https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/customizing.md#apply-the-kube-prometheus-stack
#
# However, when applying files under kube-prometheus/manifests/setup with
# kubernetes.core.k8s, we will get an error message below. Note that It
# cannot happen when applying kube-prometheus/manifests/setup with kubectl.
#
#   [ERROR]: Task failed: Module failed: Failed to load resource definition:
#   could not determine a constructor for the tag 'tag:yaml.org,2002:value'
#   in "/home/ubuntu/git/kube-prometheus/manifests/setup/0alertmanagerConfigCustomResourceDefinition.yaml",
#   line 11120, column 29
#
# This is because 0alertmanagerConfigCustomResourceDefinition.yaml has
# bare = (equal) sign in it and kubernetes.core.k8s (using pyyaml) does
# not seem to parse it as a string. See the following links for details.
#
# - https://github.com/yaml/pyyaml/issues/89
# - https://github.com/prometheus-operator/kube-prometheus/pull/2781
#
# To work around, we copy 0alertmanagerConfigCustomResourceDefinition.yaml
# into a temporary directory, patch it, and apply it.
#
- name: Create temporary file
  ansible.builtin.tempfile:
  register: kube_prometheus_tempfile
  changed_when: false

- name: Copy 0alertmanagerConfigCustomResourceDefinition.yaml as temporary file
  ansible.builtin.copy:
    src: "{{ ansible_facts['env']['HOME'] }}/git/kube-prometheus/manifests/setup/0alertmanagerConfigCustomResourceDefinition.yaml"
    dest: "{{ kube_prometheus_tempfile.path }}"
    mode: "0644"
    remote_src: true
  changed_when: false

- name: Patch temporary 0alertmanagerConfigCustomResourceDefinition.yaml
  ansible.builtin.replace:
    path: '{{ kube_prometheus_tempfile.path }}'
    regexp: '^([ ]*)- =$'
    replace: '\1- !!str ='
  changed_when: false

- name: Copy patched 0alertmanagerConfigCustomResourceDefinition.yaml into $HOME
  ansible.builtin.copy:
    src: "{{ kube_prometheus_tempfile.path }}"
    dest: "{{ ansible_facts['env']['HOME'] }}/0alertmanagerConfigCustomResourceDefinition.yaml"
    mode: "0644"
    remote_src: true

- name: Clean up temporary file
  ansible.builtin.file:
    path: "{{ kube_prometheus_tempfile.path }}"
    state: absent
  changed_when: false

- name: Apply 0alertmanagerConfigCustomResourceDefinition.yaml
  kubernetes.core.k8s:
    src: "{{ ansible_facts['env']['HOME'] }}/0alertmanagerConfigCustomResourceDefinition.yaml"
    apply: true
    server_side_apply:
      field_manager: ansible
      force_conflicts: true

- name: Find remaining files in kube-prometheus/manifests/setup
  ansible.builtin.find:
    paths: "{{ ansible_facts['env']['HOME'] }}/git/kube-prometheus/manifests/setup"
    patterns: '*.yaml'
    file_type: file
    recurse: false
    # See above comment
    excludes: 0alertmanagerConfigCustomResourceDefinition.yaml
  register: kube_prometheus_setup

- name: Apply each remaining file in kube-prometheus/manifests/setup
  kubernetes.core.k8s:
    src: "{{ item.path }}"
    apply: true
    server_side_apply:
      field_manager: ansible
      force_conflicts: true
  loop: "{{ kube_prometheus_setup.files | sort(attribute='path') }}"
  loop_control:
    label: "{{ item.path }}"

- name: Wait until all CRDs in monitoring namespace are established
  ansible.builtin.command: kubectl wait --timeout 60s --for condition=Established -n monitoring --all crds
  changed_when: false

- name: Find files in kube-prometheus/manifests
  ansible.builtin.find:
    paths: "{{ ansible_facts['env']['HOME'] }}/git/kube-prometheus/manifests"
    patterns: '*.yaml'
    file_type: file
    recurse: false
  register: kube_prometheus_manifests

- name: Apply each file in kube-prometheus/manifests
  kubernetes.core.k8s:
    src: "{{ item.path }}"
  loop: "{{ kube_prometheus_manifests.files | sort(attribute='path') }}"
  loop_control:
    label: "{{ item.path }}"

- name: Wait until all pods in monitoring namespace are ready
  ansible.builtin.command: kubectl wait --timeout 180s --for condition=Ready -n monitoring --all pods
  changed_when: false
