apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      initContainers:
        - name: metrics-extension
          env:
            - name: EXTENSION_NAME
              value: metrics
            - name: EXTENSION_ENABLED
              value: "true"
            - name: EXTENSION_URL
              value: https://github.com/argoproj-labs/argocd-extension-metrics/releases/download/v1.0.0/extension.tar.gz
          image: quay.io/argoproj/argocd-extn-installer:rc7
          imagePullPolicy: Always
          volumeMounts:
            - name: extensions
              mountPath: /tmp/extensions/
          securityContext:
            runAsUser: 100
            allowPrivilegeEscalation: false
        - name: logsummary-extension
          env:
            - name: EXTENSION_NAME
              value: logsummary
            - name: EXTENSION_ENABLED
              value: "true"
            - name: EXTENSION_URL
              value: https://github.com/numaproj-labs/argocd-extn-log-summary/releases/download/v0.0.1/extension.tar.gz
          image: quay.io/argoproj/argocd-extn-installer:rc7
          imagePullPolicy: Always
          volumeMounts:
            - name: extensions
              mountPath: /tmp/extensions/
          securityContext:
            runAsUser: 100
            allowPrivilegeEscalation: false
      containers:
        - name: argocd-server
          volumeMounts:
            - mountPath: /tmp/extensions/
              name: extensions
      volumes:
      - name: extensions
        emptyDir: {}


