- name: Add Kubernetes repository
  become: true
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: deb
    uris: "https://pkgs.k8s.io/core:/stable:/v{{ kubeadm_install.repo_ver }}/deb/"
    suites: /
    signed_by: "https://pkgs.k8s.io/core:/stable:/v{{ kubeadm_install.repo_ver }}/deb/Release.key"

- name: Add CRI-O repository
  become: true
  ansible.builtin.deb822_repository:
    name: cri-o
    types: deb
    uris: "https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v{{ kubeadm_install.repo_ver }}/deb/"
    suites: /
    signed_by: "https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v{{ kubeadm_install.repo_ver }}/deb/Release.key"

- name: Install Kubernetes and CRI-O
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - kubeadm={{ kubeadm_install.k8s_ver }}
      - kubelet={{ kubeadm_install.k8s_ver }}
      - kubectl={{ kubeadm_install.k8s_ver }}
      - cri-o={{ kubeadm_install.crio_ver }}

- name: Hold Kubernetes and CRI-O
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubelet
    - kubectl
    - cri-o
