apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/disks/pv1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage # change this field according to the Storage Class being used
---