apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: ascii-art-pipeline
spec:
  templates:
    vertex:
      metadata:
        annotations:
          numaflow.numaproj.io/callback: "true"
  vertices:
    - name: in
      scale:
        min: 1
      source:
        serving:
          service: true
          msgIDHeaderKey: "X-Numaflow-Id"
          store:
            url: "redis://redis:6379"

    - name: planner
      scale:
        min: 1
      udf:
        container:
          image: ascii:0.1
          args:
            - planner

    - name: tiger
      scale:
        min: 1
      udf:
        container:
          image: ascii:0.1
          args:
            - tiger

    - name: dog
      scale:
        min: 1
      udf:
        container:
          image: ascii:0.1
          args:
            - dog

    - name: elephant
      scale:
        min: 1
      udf:
        container:
          image: ascii:0.1
          args:
            - elephant

    - name: asciiart
      scale:
        min: 1
      udf:
        container:
          image: ascii:0.1
          args:
            - asciiart

    - name: serve-sink
      scale:
        min: 1
      sink:
        udsink:
          container:
            image: servesink:0.1
            env:
              - name: NUMAFLOW_CALLBACK_URL_KEY
                value: "X-Numaflow-Callback-Url"
              - name: NUMAFLOW_MSG_ID_HEADER_KEY
                value: "X-Numaflow-Id"

    - name: error-sink
      scale:
        min: 1
      sink:
        udsink:
          container:
            image: servesink:0.1
            env:
              - name: NUMAFLOW_CALLBACK_URL_KEY
                value: "X-Numaflow-Callback-Url"
              - name: NUMAFLOW_MSG_ID_HEADER_KEY
                value: "X-Numaflow-Id"

  edges:
    - from: in
      to: planner
    - from: planner
      to: asciiart
      conditions:
        tags:
          operator: or
          values:
            - asciiart
    - from: planner
      to: tiger
      conditions:
        tags:
          operator: or
          values:
            - tiger
    - from: planner
      to: dog
      conditions:
        tags:
          operator: or
          values:
            - dog
    - from: planner
      to: elephant
      conditions:
        tags:
          operator: or
          values:
            - elephant
    - from: tiger
      to: serve-sink
    - from: dog
      to: serve-sink
    - from: elephant
      to: serve-sink
    - from: asciiart
      to: serve-sink
    - from: planner
      to: error-sink
      conditions:
        tags:
          operator: or
          values:
            - error
