# See https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
- name: Add libnvidia-container repository
  become: true
  ansible.builtin.deb822_repository:
    name: nvidia-container-toolkit
    types: deb
    uris: "https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH)"
    suites: /
    signed_by: https://nvidia.github.io/libnvidia-container/gpgkey

- name: Install nvidia-container-toolkit
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: nvidia-container-toolkit
